# Welcome to Serverless!
service: randomzy
provider:
  name: aws
  region: eu-west-3
  runtime: python3.7
  memorySize: 3008
  timeout: 900
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - arn:aws:s3:::${env:BUCKET}
            - arn:aws:s3:::${env:BUCKET}/*

package:
  patterns:
    - "!node_modules/**"
    - "!venv/**"
    - "!**__pycache__/**"

functions:
  generate_users:
    handler: handler.main
    environment:
      access_key: ${env:ACCESS_KEY}
      secret_key: ${env:SECRET_KEY}
      bucket: ${env:BUCKET}

custom:
  region: eu-west-3
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  - serverless-python-requirements
